import { Integration } from './types'

export const integrations: Integration[] = [
	{
		name: 'MetaMask',
		logo: 'metamask.svg',
		link: 'https://metamask.io/',
		type: 'wallet',
	},
	{
		name: 'Privy',
		logo: 'privy.png',
		link: 'https://www.privy.io/',
		type: 'tool',
	},
	{
		name: 'Rainbow',
		logo: 'rainbow.png',
		link: 'https://rainbow.me/',
		type: 'wallet',
	},
	{
		name: 'Guild',
		logo: 'guild.png',
		link: 'https://guild.xyz/',
		type: 'app',
	},
	{
		name: 'WalletConnect',
		logo: 'walletconnect.png',
		link: 'https://walletconnect.com/',
		type: 'tool',
	},
	{
		name: 'OpenSea',
		logo: 'opensea.svg',
		link: 'https://opensea.io/',
		type: 'app',
	},
	{
		name: 'Snapshot',
		logo: 'snapshot.png',
		link: 'https://snapshot.org/',
		type: 'app',
	},
	{
		name: 'Tally',
		logo: 'tally.png',
		link: 'https://tally.xyz/',
		type: 'app',
	},
	{
		name: 'Gnosis',
		logo: 'gnosis.png',
		link: 'https://safe.global/',
		type: 'wallet',
	},
	{
		name: 'Ethereum identity kit',
		logo: 'eik.svg',
		link: 'https://ethidentitykit.com',
		type: 'tool',
	},
	{
		name: 'ronin wallet',
		logo: 'ronin.svg',
		link: 'https://wallet.roninchain.com/',
		type: 'wallet',
	},
	{
		name: 'gemini wallet',
		logo: 'gemini.svg',
		link: 'https://www.gemini.com/',
		type: 'wallet',
	},
	{
		name: 'Vision',
		logo: 'vision.png',
		link: 'https://vision.io/',
		type: 'app',
	},
	{
		name: 'Superfluid',
		logo: 'superfluid.png',
		link: 'https://superfluid.finance/',
		type: 'app',
	},
	{
		name: 'Magic Eden',
		logo: 'magiceden.png',
		link: 'https://magiceden.io/',
		type: 'app',
	},
	{
		name: 'Paragraph',
		logo: 'paragraph.svg',
		link: 'https://paragraph.com/',
		type: 'app',
	},
	{
		name: 'Taho',
		logo: 'taho.svg',
		link: 'https://taho.xyz/',
		type: 'wallet',
	},
	{
		name: 'Dynamic',
		logo: 'dynamic.png',
		link: 'https://dynamic.xyz/',
		type: 'tool',
	},
	{
		name: '1inch',
		logo: '1inch.svg',
		link: 'https://1inch.io/',
		type: 'wallet',
	},
	{
		name: 'Ceramic',
		logo: 'ceramic.png',
		link: 'https://ceramic.network/',
		type: 'app',
	},
	{
		name: 'Farcaster',
		logo: 'farcaster.svg',
		link: 'https://farcaster.xyz/',
		type: 'app',
	},
	{
		name: 'Lens',
		logo: 'lens.svg',
		link: 'https://lens.xyz/',
		type: 'app',
	},
	{
		name: 'Fileverse',
		logo: 'fileverse.svg',
		link: 'https://fileverse.io/',
		type: 'app',
	},
	{
		name: 'RainbowKit',
		logo: 'rainbowkit.png',
		link: 'https://rainbowkit.com/',
		type: 'tool',
	},
	{
		name: 'Galxe',
		logo: 'galaxe.svg',
		link: 'https://galxe.xyz/',
		type: 'app',
	},
	{
		name: 'Foundation',
		logo: 'foundation.png',
		link: 'https://foundation.app/',
		type: 'app',
	},
	{
		name: 'Shape.network',
		logo: 'shapenetwork.png',
		link: 'https://shape.network/',
		type: 'app',
	},
	{
		name: 'oncyber',
		logo: 'oncyber.png',
		link: 'https://cyber.xyz/',
		type: 'app',
	},
	{
		name: 'radicle',
		logo: 'radicle.svg',
		link: 'https://radicle.xyz/',
		type: 'app',
	},
	{
		name: 'Unlock Protocol',
		logo: 'unlock-protocol.svg',
		link: 'https://unlock-protocol.com/',
		type: 'app',
	},
	{
		name: 'Yup',
		logo: 'yup.svg',
		link: 'https://yup.io/',
		type: 'app',
	},
	{
		name: 'Zerion',
		logo: 'zerion.svg',
		link: 'https://zerion.io/',
		type: 'wallet',
	},
	{
		name: 'Trust Wallet',
		logo: 'trust.svg',
		link: 'https://trustwallet.io/',
		type: 'wallet',
	},
	{
		name: 'OKX Wallet',
		logo: 'okx.svg',
		link: 'https://www.okx.com/',
		type: 'wallet',
	},
	{
		name: 'Binance',
		logo: 'binance.svg',
		link: 'https://www.binance.com/',
		type: 'wallet',
	},
	{
		name: 'bitget wallet',
		logo: 'bitget.svg',
		link: 'https://web3.bitget.com/',
		type: 'wallet',
	},
	{
		name: 'Frame',
		logo: 'frame.png',
		link: 'https://frame.sh/',
		type: 'wallet',
	},
	{
		name: 'TokenPocket',
		logo: 'tokenpocket.svg',
		link: 'https://www.tokenpocket.pro/',
		type: 'wallet',
	},
	{
		name: 'uniswap wallet',
		logo: 'uniswap.svg',
		link: 'https://wallet.uniswap.org/',
		type: 'wallet',
	},
	{
		name: 'track aurora',
		logo: 'trackaurora.png',
		link: 'https://trackaurora.com/',
		type: 'app',
	},
	{
		name: 'best wallet',
		logo: 'best-wallet.svg',
		link: 'https://bestwallet.com/',
		type: 'wallet',
	},
	{
		name: 'Ledger',
		logo: 'ledger.svg',
		link: 'https://ledger.com/',
		type: 'wallet',
	},
	{
		name: 'bybit wallet',
		logo: 'bybit.svg',
		link: 'https://bybit.com/',
		type: 'wallet',
	},
	{
		name: 'bitfrost wallet',
		logo: 'bitfrost.svg',
		link: 'https://bitfrost.com/',
		type: 'wallet',
	},
	{
		name: 'xPortal',
		logo: 'xportal.svg',
		link: 'https://xportal.com',
		type: 'wallet',
	},
	{
		name: 'crypto.com',
		logo: 'cryptodotcom.svg',
		link: 'https://crypto.com/',
		type: 'wallet',
	},
	{
		name: 'imToken',
		logo: 'imtoken.svg',
		link: 'https://token.im/',
		type: 'wallet',
	},
	{
		name: 'blockchain.com',
		logo: 'blockchain.svg',
		link: 'https://blockchain.com/',
		type: 'wallet',
	},
	{
		name: 'BitPay',
		logo: 'bitpay.svg',
		link: 'https://bitpay.com/',
		type: 'wallet',
	},
	{
		name: 'rakuten wallet',
		logo: 'rakuten.png',
		link: 'https://www.rakuten-wallet.co.jp/',
		type: 'wallet',
	},
	{
		name: 'arculus',
		logo: 'arculus.svg',
		link: 'https://getarculus.com/',
		type: 'wallet',
	},
	{
		name: 'ctrl wallet',
		logo: 'ctrl.svg',
		link: 'https://ctrl.xyz/',
		type: 'wallet',
	},
	{
		name: 'Common Ground',
		logo: 'commonground.png',
		link: 'https://app.cg/',
		type: 'app',
	},
	{
		name: 'Paper.ink',
		logo: 'paper.png',
		link: 'https://paper.ink/',
		type: 'app',
	},
]
